### ISSUE TITLE
The difference in AUC metrics of the AKT model

### ISSUE THREAD

**Issue by RingoTC** [UpstageAI/cl4kt#1]
The original paper of AKT shows it can achieve 0.8346 in the ASSISTments2009 dataset.
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/6525061/209438614-c9cfd3d4-6098-4cda-97cd-b63651e060fd.png">

However, in your paper, AKT can only achieve 0.7532 in the ASSISTments2009 dataset. Is there some difference in the implementation of AKT? 
 
<img width="823" alt="image" src="https://user-images.githubusercontent.com/6525061/209438668-ecefcf18-4809-43e1-9ad0-96f32b78305a.png">

**Comment by aporia3517** [comment]
I am sorry for the late reply. The reason for the different performance is that different preprocessing steps were applied to the same data. As mentioned in Section 4.1.3 of the paper, we consider the last 100 interactions for each student because we focus on the recent information essential for predicting the future.
